<!--=========-->
<section class="service-section" app-section="service">
    <div class="container">

        <div class="row service-container align-items-start">

            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 service">
                <div class="clearfix border-right-dashed">

                    <div class="image-box float-left">
                        <img src="src/img/phone.png" alt="" />
                    </div>

                    <div class="image-text float-left">
                        <h2 class="title">Call Now</h2>
                        <p><a href="tel:+2348169336721"  class="text-white">+2348169336721</a></p>
                        <p><a href="tel:+2348086954746"  class="text-white">+2348086954746</a></p>
                    </div>

                </div>
            </div>


            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 service">
                <div class="clearfix border-right-dashed">

                    <div class="image-box float-left">
                        <img src="src/img/email.png" alt="" />
                    </div>

                    <div class="image-text float-left contact-information">
                        <h2 class="title">Email us</h2>
                        <p><a href="mailto:FoodieNex@support.com" class="text-white">FoodieNex@support.com</a></p>
                        <p><a href="mailto:FoodieNex@gmail.com"  class="text-white">FoodieNex@gmail.com</a></p>
                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 service">
                <div class="clearfix">
                    <div class="image-box float-left">
                        <img src="src/img/map.png" alt="" />
                    </div>

                    <div class="image-text float-left contact-information">
                        <h2 class="title">Address</h2>
                        <p><a class="text-white" href="#">Lekki phase 1<br> Lagos   (state), UAR</a></p>
                    </div>
                </div>
            </div>

        </div>

    </div>
</section>
<!--=========-->