
<footer class="footer" app-section="footer">

    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 column">
                    <div class="footer-top-content">
                        <div class="logo">
                            FoodieNex
                        </div>

                        <p class="text-muted col-md-7 p-0">There is a smile behind every taste, just let it our
                            :)
                        </p>
                        <ul class="social-icon-list">
                            <li>
                                <a href="#"><i class="icofont-facebook"></i></a>
                            </li>
                            <li class="social-icon custom-icon-pinterest">
                                <a href="#"><i class="icofont-pinterest"></i></a>
                            </li>
                            <li class="social-icon custom-icon-dribbble">
                                <a href="#"><i class="icofont-dribbble"></i></a>
                            </li>
                            <li class="social-icon custom-icon-twitter">
                                <a href="#"><i class="icofont-twitter"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 column">
                    <div class="contact-content">
                        <h3 class="caption">Contact Us <hr> </h3>

                        <div class="contact-info d-flex align-items-center">
                            <div class="icon">
                                <button class="custom-btn">
                                    <i class="icofont-phone"></i>
                                </button>
                            </div>
                            <div class="info">
                                <a href="tel:+2348169336721" class="link">+234 816 933 6721</a>
                                <a href="tel:+2348086954746" class="link">+234 808 695 4746</a>
                            </div>
                        </div>

                        <div class="contact-info d-flex align-items-center">
                            <div class="icon">
                                <button class="custom-btn">
                                    <i class="icofont-email"></i>
                                </button>
                            </div>
                            <div class="info">
                                <a href="mailto:ufereclinton@gmail.com" class="link">ufereclinton@gmail.com</a>
                                <a href="mailto:clintonufere@gmail.com" class="link">clintonufere@gmail.com</a>
                            </div>
                        </div>

                        <div class="contact-info d-flex align-items-center">
                            <div class="icon">
                                <button class="custom-btn">
                                    <i class="icofont-google-map"></i>
                                </button>
                            </div>
                            <div class="info">
                                <a href="#"  class="link">89 ikote-ekpene rd, Abia state, Nigeria</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-5 column">
                    <h3 class="caption">Opening Hours <hr></h3>
                    <div class="opening-hours">
                        <div class="opening-content">
                            <table class="time-table w text-center table table-borderless">

                                <tbody>
                                <tr class="not-active">
                                    <td class="t-item">Weekends</td>
                                    <td class="t-item"><span class="divider">---</span></td>
                                    <td class="t-item"><span>closed</span></td>
                                </tr>

                                <tr class="t-role">
                                    <td class="t-item">Weekdays</td>
                                    <td class="t-item"><span class="divider">---</span></td>
                                    <td class="t-item">
                                        <span>8AM</span> - <span>10PM</span>
                                    </td>
                                </tr>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="footer-bottom">
        <div class="container">
            <div class="d-flex flex-wrap justify-content-between">
                <div class="copyright-txt">
                    <p>Copyright 2020. All Rights Reserved.</p>
                </div>
                <div class="terms">
                    <span><a href="#" class="text-orange">Terms & Conditions</a> | <a href="#">Privacy Policy</a></span>
                </div>

            </div>
        </div>
    </div>
</footer>

<script src="src/js/jquery-3.5.1.min.js"></script>
<script src="src/js/popper.min.js"></script>
<script src="assets/js/aos.js"></script>
<script src="src/js/bootstrap.min.js"></script>
<script src="src/js/slick.min.js"></script>
<script src="src/js/main.js"></script>