<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="src/css/icofont.min.css" />
<link rel="stylesheet" href="src/css/bootstrap.min.css" />
<link rel="stylesheet" href="assets/remix/fonts/remixicon.css" />
<link rel="stylesheet" href="src/css/scss/custom.css" />
<link rel="stylesheet" href="src/css/scss/mobile.css" />
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="src/css/slick.css" />
<link rel="stylesheet" href="src/css/slick-theme.css" />
<link rel="stylesheet" href="src/css/aos.css" />