<div id="top-btn" app-button="scroll-top">
    <button class="btn top-btn"><i class="icofont-arrow-up"></i></button>
</div>
<!---------------------->
<header>
    <div class="header">
        <div class="highlight d-flex align-items-center flex-wrap justify-content-between p-2">

            <div class="social-links d-flex align-items-center py-2 desktop-off">
                <a href="#" class="social-link btn btn-sm text-light"><i class="ri-facebook-line"></i></a>
                <a href="#" class="social-link btn btn-sm text-light"><i class="ri-github-line"></i></a>
                <a href="#" class="social-link btn btn-sm text-light"><i class="ri-twitter-line"></i></a>
                <a href="#" class="social-link btn btn-sm text-light "><i class="ri-instagram-line"></i></a>
            </div>

            <div class="text-white px-2 timer" app-timer>
                <span><i class="icofont-clock-time"></i></span>

                <span>
                        <span data-time="hr">00</span> :
                        <span data-time="min">00</span> :
                        <span data-time="secs">00</span>
                    </span>
            </div>
        </div>


        <nav class="navbar navbar-expand-lg navbar-light py-0 px-3 d-flex">

            <div class="d-flex justify-content-between align-items-center flex-wrap">
                <a class="navbar-brand mr-3" href="<?= "./"?>">
                    <h3 class="logo">
                        <span class="text-white">FoodieNex</span>
                        <!-- <img src="img/logo.png" class="w-100 img-fluid" alt="" /> -->
                    </h3>
                </a>

                <div class="open-time ml-5 desktop-off">
                    <h6 class="text-danger" app-time-state>
                        <i class="icofont-clock-time"></i>
                        <span></span>
                    </h6>
                    <span class="text-white">8AM - 10PM</span>
                </div>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <i class="icofont-navigation-menu"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav navbar-custom">
                    <li class="nav-item">
                        <a class="nav-link" href="<?= "./"?>">Home </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Categories
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#" data-null>Recipe List</a>
                            <a class="dropdown-item" href="#" data-null="">Food Menu</a>
                            <a class="dropdown-item" href="blog" data-null>Blog</a>
                        </div>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="about">About</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="contact">Contact</a>
                    </li>

                    <li class="nav-item rg-btn">
                            <span class="nav-link">
                                <a class="text-white" href="#">Register</a>
                            </span>
                    </li>

                    <li class="nav-item last-menu-bg">
                        <span class="nav-link"><a href="#">Login</a></span>
                    </li>

                </ul>
            </div>

        </nav>

    </div>
</header>
<!--/=====-->