<section class="service-section section" app-section="service">
    <div class="container">

        <div class="row service-container align-items-start">

            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 service">
                <div class="clearfix border-right-dashed">

                    <div class="image-box float-left">
                        <img src="src/img/honney.png" alt="" />
                    </div>

                    <div class="image-text float-left">
                        <h2 class="title">Choose service</h2>
                        <p class="info">Make a selection from any of our services (food, recipe & pastries)</p>
                    </div>

                </div>
            </div>


            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 service">
                <div class="clearfix border-right-dashed">

                    <div class="image-box float-left">
                        <img src="src/img/macaron.png" alt="" />
                    </div>

                    <div class="image-text float-left">
                        <h2 class="title">place order</h2>
                        <p class="info">Once you've placed an order, it will take couple of minutes or hour to
                            arrive.</p>
                    </div>
                </div>
            </div>


            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 service">
                <div class="clearfix">
                    <div class="image-box float-left">
                        <img src="src/img/dinner.png" alt="" />
                    </div>
                    <div class="image-text float-left">
                        <h2 class="title">Pay & go</h2>
                        <p class="info">Customers are allowed to make payment after delivery. But this is limited on
                            clients location.</p>
                    </div>
                </div>
            </div>

        </div>

    </div>
</section>
