<section class="special-section section" app-section="special">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-6 col-xl-6 img-wrapper" data-aos="fade-right"
                 data-aos-delay="150">
                <div class="special-img">
                    <img src="src/img/cakes/chocolate.jpg" class="w-100" alt="" />
                </div>
            </div>

            <div class="col-sm-12 col-md-7 col-lg-6 col-xl-6 content" data-aos="fade-up" data-aos-delay="200">
                <div class="special-content text-center">

                    <div class="donut-icon m-auto">
                        <img src="src/img/donut.png" class="w-100" alt="" />
                    </div>
                    <div class="menu-head">
                        <h2 class="title">
                            Today’s Special
                            <span>Recipe For You</span>
                        </h2>
                    </div>

                    <h4 class="mb-3">Chocolate Cake</h4>
                    <p class="des">
                        We have different chocolate recipes that you can try anywhere(office/home). One thing about
                        our recipes is that, no matter the weather or the equipment you used, provided you used the
                        quantity we labelled out for you and apply them as instructed, you'll definitely get a good
                        result.
                    </p>
                    <div class="offer-info">
                        <div class="form-row justify-content-center align-items-center">
                            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                                <div class="item-price">
                                    <h3><span>$</span>30.00</h3>
                                    <span><i class="icofont-clock-time"></i> 10 min ago</span>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                                <div class="item-number">
                                    <div class="item-quantity">
                                        <button data-button="increment"><i class="icofont-plus"></i></button>
                                        <span>05</span>
                                        <button data-button="decrement"><i class="icofont-minus"></i></button>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                                <a href="#" class="btn order-btn">Order Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>